version: "3.3" 
services:
  mapper:
    build: .
    volumes:
      - ./data:/app/data
      - ./mappings:/app/mappings
    environment:
      DATASET: RCEbeeldbank
      CONFIG: ./mappings/config.json
    command: bin/harvest-and-transform.sh
